-- Seed the menu from the bundled snapshot in src/data/menu.js.
-- Prices there are whole EGP; stored here as piastres (x100).
-- Idempotent: re-running updates names/prices rather than duplicating rows.

insert into public.menu_categories (slug, name, tagline, note, sort_order) values
('breakfast', 'Breakfast', 'Served from open until noon', 'Eggs cracked to order, on bread we laminated the same morning.', 0),
('bakeries', 'Bakeries', 'Laminated by hand, baked at 4am', 'Seventy-two hours of cold ferment before anything meets the oven.', 1),
('hot-coffee', 'Hot Coffee', 'The classics, pulled properly', 'House blend as standard. Ask for the single origin on bar today.', 2),
('ice-coffee', 'Ice Coffee', 'Built over slow-melt ice', 'Blended options are shaken, then spun — never watery.', 3),
('matcha', 'Matcha', 'Ceremonial grade, whisked to order', 'Stone-milled and sifted daily — nothing sits open past service.', 4),
('signatures', 'Signatures', 'Only at Solis', 'Our own recipes. Half of them started as a staff experiment.', 5),
('lemonade', 'Refresh Lemonade', 'Pressed fruit, no syrup shortcuts', 'Every one of them is the same price. Order two.', 6),
('hot-drinks', 'Hot Drinks', 'For the non-coffee table', 'Chocolate is melted, not scooped from a powder tin.', 7),
('retail', 'Retail Beans', 'Take the roast home — 250g bags', 'Roasted in small batches. We grind to your brewer at the counter, free.', 8)
on conflict (slug) do update set
  name = excluded.name, tagline = excluded.tagline,
  note = excluded.note, sort_order = excluded.sort_order;

insert into public.menu_items (category_id, name, price_piastres, meta, is_signature, sort_order)
select c.id, v.name, v.price_piastres, v.meta, v.is_signature, v.sort_order
from (values
('breakfast', 'Mushroom Egg', 24500, null, false, 0),
('breakfast', 'Egg & Shallal Cheese Croissant', 28000, null, false, 1),
('breakfast', 'Creamy Salmon Egg', 39000, null, false, 2),
('breakfast', 'Buffalo Beef', 34500, null, false, 3),
('breakfast', 'Sausage Egg', 26500, null, false, 4),
('breakfast', 'Egg Benedict Smoked Salmon', 38500, null, false, 5),
('bakeries', 'Plain Croissant', 9500, null, false, 0),
('bakeries', 'Pain Suisse', 13500, null, false, 1),
('bakeries', 'Olive & Cheese Croissant', 14500, null, false, 2),
('bakeries', 'Pistachio Croissant', 15000, null, false, 3),
('bakeries', 'Almond Croissant', 15500, null, false, 4),
('bakeries', 'Blueberry Danish', 18500, null, false, 5),
('bakeries', 'Mix Cheese Croissant', 26500, null, false, 6),
('bakeries', 'Turkey Cheese Croissant', 28500, null, false, 7),
('bakeries', 'Roast Beef Croissant', 38500, null, false, 8),
('hot-coffee', 'Espresso', 7500, null, false, 0),
('hot-coffee', 'Espresso Macchiato', 9500, null, false, 1),
('hot-coffee', 'Americano', 9500, null, false, 2),
('hot-coffee', 'Cortado', 10000, null, false, 3),
('hot-coffee', 'Flat White', 10500, null, false, 4),
('hot-coffee', 'Latte', 11000, null, false, 5),
('hot-coffee', 'Cappuccino', 11000, null, false, 6),
('hot-coffee', 'Espresso Affogato', 12500, null, false, 7),
('hot-coffee', 'Espresso Con Panna', 13000, null, false, 8),
('hot-coffee', 'Spanish Latte', 15000, null, false, 9),
('hot-coffee', 'Mocha', 15000, null, false, 10),
('hot-coffee', 'White Mocha', 15000, null, false, 11),
('hot-coffee', 'Caramel Macchiato', 16500, null, false, 12),
('hot-coffee', 'Hot Pistachio Latte', 19500, null, false, 13),
('ice-coffee', 'Ice Americano', 10500, null, false, 0),
('ice-coffee', 'Ice Latte', 11500, null, false, 1),
('ice-coffee', 'Frappuccino', 12500, null, false, 2),
('ice-coffee', 'Ice Spanish Latte', 16000, null, false, 3),
('ice-coffee', 'Ice Mocha', 16000, null, false, 4),
('ice-coffee', 'Iced Creamy White Mocha', 16500, null, false, 5),
('ice-coffee', 'Ice Caramel Macchiato', 17000, null, false, 6),
('ice-coffee', 'Blended Ice Spanish Latte', 17500, null, false, 7),
('ice-coffee', 'Blended Ice White Mocha', 18500, null, false, 8),
('ice-coffee', 'Ice Pistachio Latte', 18500, null, false, 9),
('ice-coffee', 'Blended Pistachio Latte', 19500, null, false, 10),
('matcha', 'Hot Spanish Matcha', 17500, null, false, 0),
('matcha', 'Coconut Matcha Cloud', 19000, null, false, 1),
('matcha', 'Banana Bread Matcha', 19000, null, false, 2),
('matcha', 'Ice White Chocolate Matcha', 19500, null, false, 3),
('matcha', 'Mango Matcha Cloud', 20500, null, false, 4),
('matcha', 'Cherry Matcha Cloud', 23500, null, false, 5),
('signatures', 'Passion Orange Soda', 14500, null, false, 0),
('signatures', 'Mango Coconut', 15000, null, false, 1),
('signatures', 'Hot Matcha', 16000, null, false, 2),
('signatures', 'Ice Matcha', 16000, null, false, 3),
('signatures', 'Peach Vanilla Milkshake', 16500, null, false, 4),
('signatures', 'Blue Pineapple Smoothie', 16500, null, false, 5),
('signatures', 'Coffee Cream', 17500, null, false, 6),
('signatures', 'Ice Spanish Matcha', 17500, null, false, 7),
('signatures', 'MC Splash', 17500, null, false, 8),
('signatures', 'Cream Caramel Latte', 17500, null, false, 9),
('signatures', 'Strawberry Matcha', 18000, null, false, 10),
('signatures', 'Banana Caramel Milkshake', 18500, null, false, 11),
('signatures', 'Salted Vanilla Latte', 18500, null, false, 12),
('signatures', 'Piña Colada', 19000, null, false, 13),
('signatures', 'Matcha Coconut', 19500, null, false, 14),
('signatures', 'Pistachio Blend Milkshake', 19500, null, false, 15),
('signatures', 'Berry Mood', 19500, null, false, 16),
('signatures', 'Strawberry Coconut Matcha', 21500, null, false, 17),
('signatures', 'Banoffee Latte', 24500, null, false, 18),
('signatures', 'Blended Pistachio Matcha', 26500, null, false, 19),
('signatures', 'Sun Set', 26500, null, true, 20),
('lemonade', 'Pink Lemonade', 15000, null, false, 0),
('lemonade', 'Blueberry Lemonade', 15000, null, false, 1),
('lemonade', 'Mango Passion', 15000, null, false, 2),
('lemonade', 'Coconut Pineapple', 15000, null, false, 3),
('lemonade', 'Mango Peach', 15000, null, false, 4),
('lemonade', 'Mix Berries', 15000, null, false, 5),
('hot-drinks', 'Tea', 6000, null, false, 0),
('hot-drinks', 'Hot Cider', 12500, null, false, 1),
('hot-drinks', 'Hot Chocolate', 16000, null, false, 2),
('hot-drinks', 'Strawberry Hot Chocolate', 18000, null, false, 3),
('hot-drinks', 'Honey Cinnamon Latte', 18500, null, false, 4),
('hot-drinks', 'Peanut Butter Latte', 19000, null, false, 5),
('retail', 'Brazil Cerrado', 55000, '250g', false, 0),
('retail', 'Ethiopia Guji', 75000, '250g', false, 1),
('retail', 'Colombia Pink Bourbon', 90000, '250g', false, 2),
('retail', 'Colombia Infused Peach', 145000, '250g', false, 3)
) as v(slug, name, price_piastres, meta, is_signature, sort_order)
join public.menu_categories c on c.slug = v.slug;